//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mission3_GSB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gsbrapportEntities : DbContext
    {
        public gsbrapportEntities()
            : base("name=gsbrapportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<famille> famille { get; set; }
        public virtual DbSet<medecin> medecin { get; set; }
        public virtual DbSet<medicament> medicament { get; set; }
        public virtual DbSet<offrir> offrir { get; set; }
        public virtual DbSet<rapport> rapport { get; set; }
        public virtual DbSet<visiteur> visiteur { get; set; }
    }
}
